apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  labels:
    app: flask-realworld-example-app
data:
  DATABASE_URL: postgresql://{{.Env.DB_USER}}:{{.Env.DB_PASSWORD}}@postgres/flask
  FLASK_DEBUG: "false"
  HTTP_PORT: "80"
