apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: flask
  POSTGRES_USER: {{.Env.DB_USER}}
  POSTGRES_PASSWORD: {{.Env.DB_PASSWORD}}
  PGDATA: /var/lib/postgresql/data/pgdata
